// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://syjhhartqaivdxibpxiy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN5amhoYXJ0cWFpdmR4aWJweGl5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNjg3NjQsImV4cCI6MjA2Nzc0NDc2NH0.v08l1Fxoho6hDxhg2NZtN_i637QZYmRYbGBHw3o6-mw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});